services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 301199
      MYSQL_DATABASE: cp3_devops
      MYSQL_USER: maicon
      MYSQL_PASSWORD: rm5611279
    ports:
      - "3306:3306"
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - api-produto-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  api-produto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-produto
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: cp3_devops
      MYSQL_USER: maicon
      MYSQL_PASSWORD: rm5611279
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - api-produto-network

networks:
  api-produto-network:

volumes:
  database-volume: